# YOUR NAME OR TITLE OF YOUR SITE
name: yeacark links

# YOUR BRAND/PERSONAL TAGLINE
tagline: bella :p
# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/yeacark/yeacark.github.io/images/carkyboi.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://github.com/yeacark/yeacark.github.io/images/banner2.jpeg

# SOCIAL MEDIA
links:
    # INSTAGRAM
- Name: Instagram
    URL: https://www.instagram.com
    Username: 222fxde
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: yeaacark
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com
    Username: '@yeacark'
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: yeacark
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # TWITCH
  - Name: Twitch
    URL: https://twitch.tv
    Username: cark_irl
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

     # DISCORD
   - Name: Server Discord
     URL: 'https://dsc.gg'
     Username: cark
     Icon-Class: fab fa-discord
     Color: '#5865F2'
     Text_Color: '#ffffff'

       # DISCORD
   - Name: Invita carkbot!
     URL: 'https://dsc.gg'
     Username: carkbot
     Icon-Class: fab fa-discord
     Color: '#5865F2'
     Text_Color: '#ffffff'

      # GITHUB
  - Name: Pagina GitHub di carkbot
    URL: http://github.com
    Username: yeacark/carkbot
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # SPOTIFY
  - Name: Spotify
    URL: https://open.spotify.com/user/
    Username: 5wwwnfjkomp9pp7lyuis3aqir
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
